import { mkdirSync, writeFileSync, existsSync, unlinkSync } from "node:fs";
import { join, dirname } from "node:path";
import { memoryRoot } from "./paths.js";

export type ServicePlatform = "linux" | "darwin";

/**
 * Snapshot the install-time environment for the daemon's EnvironmentFile / plist,
 * so the generated config is portable (no machine-specific paths baked in here).
 * Order is stable. Never includes qmd's QMD_EMBED_MODEL (that is qmd's Qwen3-8B,
 * independent of qmemd) — but DOES capture qmemd's own QMEMD_EMBED_MODEL when set
 * (qmemd-rkl): it must travel WITH QMEMD_DB, since the daemon and the CLI share that
 * one index, and a daemon falling back to the default model while the CLI uses an
 * override would write mismatched vectors into the shared index and break hybrid recall.
 */
export function captureDaemonEnv(
  platform: ServicePlatform,
  env: NodeJS.ProcessEnv = process.env,
): Array<[string, string]> {
  const pairs: Array<[string, string]> = [];
  pairs.push(["QMD_MEMORY_DIR", env.QMD_MEMORY_DIR || memoryRoot()]);
  if (env.PATH) pairs.push(["PATH", env.PATH]);
  if (platform === "linux" && env.LD_LIBRARY_PATH) pairs.push(["LD_LIBRARY_PATH", env.LD_LIBRARY_PATH]);
  // XDG_CACHE_HOME governs indexDbPath() via cacheDir() when QMEMD_DB is unset (qp-daemon-index-
  // identity-health-0lq). A systemd --user daemon never sources .bashrc, so without capturing it
  // the daemon opens an empty ~/.cache/qmemd index while the CLI writes under $XDG_CACHE_HOME —
  // /health rootHash (sha of QMD_MEMORY_DIR) still matches, so hybrid recall delegates and returns
  // hits:[] though facts exist. Captured alongside QMEMD_DB, the other index-location input.
  if (env.XDG_CACHE_HOME) pairs.push(["XDG_CACHE_HOME", env.XDG_CACHE_HOME]);
  if (env.QMEMD_DB) pairs.push(["QMEMD_DB", env.QMEMD_DB]);
  if (env.QMEMD_EMBED_MODEL) pairs.push(["QMEMD_EMBED_MODEL", env.QMEMD_EMBED_MODEL]);
  return pairs;
}

export interface ServiceExec {
  bin: string;   // runtime, e.g. /home/.../bun
  entry: string; // CLI entry script, e.g. /home/.../dist/cli/qmemd.js
}

export interface ServiceDirs {
  systemdUser: string;   // Linux unit dir
  qmemdConfig: string;   // Linux daemon.env dir
  launchAgents: string;  // macOS plist dir
  macLogs: string;       // macOS stdout/stderr log dir
}

export interface ServiceOpts {
  port: number;
  exec: ServiceExec;
  env: Array<[string, string]>;
  dirs: ServiceDirs;
}

export interface ServiceFile {
  path: string;
  content: string;
}

export interface ServiceArtifacts {
  files: ServiceFile[];
  activation: string[];
  deactivation: string[];
}

const SYSTEMD_UNIT_NAME = "qmemd-mcp.service";

/** Pure: build the OS-init artifacts for a platform. No fs, no process reads. */
export function serviceArtifacts(platform: ServicePlatform, opts: ServiceOpts): ServiceArtifacts {
  if (platform === "linux") return linuxArtifacts(opts);
  if (platform === "darwin") return darwinArtifacts(opts);
  throw new Error(`unsupported platform '${platform}' (need linux or darwin)`);
}

function envFileBody(env: Array<[string, string]>): string {
  const header = [
    "# Environment for the qmemd-mcp systemd user service (Streamable HTTP MCP daemon).",
    "# Generated by `qmemd mcp install-service` — captures the install-time environment.",
    "#",
    "# qmemd uses its OWN embedding model (embeddinggemma-300M via QMEMD_EMBED_MODEL, default).",
    "# Do NOT set qmd's model var here — that is qmd's Qwen3-8B and is independent of qmemd.",
  ];
  const lines = env.map(([k, v]) => `${k}=${v}`);
  return [...header, ...lines].join("\n") + "\n";
}

function linuxArtifacts(opts: ServiceOpts): ServiceArtifacts {
  const { port, exec, env, dirs } = opts;
  const envPath = join(dirs.qmemdConfig, "daemon.env");
  const unitPath = join(dirs.systemdUser, SYSTEMD_UNIT_NAME);
  const unit = [
    "[Unit]",
    `Description=qmemd MCP server (Streamable HTTP) — shared memory daemon on :${port}`,
    "Documentation=https://github.com/tobilu/qmemd",
    "After=network.target",
    "",
    "[Service]",
    "Type=simple",
    "WorkingDirectory=%h",
    `EnvironmentFile=${envPath}`,
    `ExecStart=${exec.bin} ${exec.entry} mcp --http --port ${port}`,
    "Restart=always",
    "RestartSec=2",
    "",
    "[Install]",
    "WantedBy=default.target",
    "",
  ].join("\n");
  return {
    files: [
      { path: unitPath, content: unit },
      { path: envPath, content: envFileBody(env) },
    ],
    activation: [
      "loginctl enable-linger",
      "systemctl --user daemon-reload",
      `systemctl --user enable --now ${SYSTEMD_UNIT_NAME}`,
    ],
    deactivation: [
      `systemctl --user disable --now ${SYSTEMD_UNIT_NAME}`,
      "systemctl --user daemon-reload",
    ],
  };
}

const LAUNCHD_LABEL = "io.qmemd.mcp";

function escapeXml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function darwinArtifacts(opts: ServiceOpts): ServiceArtifacts {
  const { port, exec, env, dirs } = opts;
  const plistPath = join(dirs.launchAgents, `${LAUNCHD_LABEL}.plist`);
  const logPath = join(dirs.macLogs, "qmemd-mcp.log");
  const args = [exec.bin, exec.entry, "mcp", "--http", "--port", String(port)];
  const argXml = args.map(a => `    <string>${escapeXml(a)}</string>`).join("\n");
  const envXml = env
    .map(([k, v]) => `    <key>${escapeXml(k)}</key>\n    <string>${escapeXml(v)}</string>`)
    .join("\n");
  const plist = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">`,
    `<plist version="1.0">`,
    `<dict>`,
    `  <key>Label</key>`,
    `  <string>${LAUNCHD_LABEL}</string>`,
    `  <key>ProgramArguments</key>`,
    `  <array>`,
    argXml,
    `  </array>`,
    `  <key>EnvironmentVariables</key>`,
    `  <dict>`,
    envXml,
    `  </dict>`,
    `  <key>RunAtLoad</key>`,
    `  <true/>`,
    `  <key>KeepAlive</key>`,
    `  <true/>`,
    `  <key>StandardOutPath</key>`,
    `  <string>${escapeXml(logPath)}</string>`,
    `  <key>StandardErrorPath</key>`,
    `  <string>${escapeXml(logPath)}</string>`,
    `</dict>`,
    `</plist>`,
    ``,
  ].join("\n");
  return {
    files: [{ path: plistPath, content: plist }],
    activation: [`launchctl bootstrap gui/$(id -u) ${plistPath}`],
    deactivation: [`launchctl bootout gui/$(id -u)/${LAUNCHD_LABEL}`],
  };
}

/** Write every artifact file, creating parent dirs. */
export function writeArtifacts(artifacts: ServiceArtifacts): void {
  for (const f of artifacts.files) {
    mkdirSync(dirname(f.path), { recursive: true });
    writeFileSync(f.path, f.content);
  }
}

/** Remove any artifact files that exist; return the paths actually removed. */
export function removeArtifacts(artifacts: ServiceArtifacts): string[] {
  const removed: string[] = [];
  for (const f of artifacts.files) {
    if (existsSync(f.path)) {
      unlinkSync(f.path);
      removed.push(f.path);
    }
  }
  return removed;
}
